namespace FooNamespace.Tests;
[TestClass]
public class Boo_Tests
{
    [TestMethod]
    public void Method1()
    {
        Assert.Fail("autogenerated");
    }

    [TestMethod]
    public void Method2()
    {
        Assert.Fail("autogenerated");
    }
}